# Generated by Django 5.2.12 on 2026-03-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='asin',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
