# Generated by Django 4.2.11 on 2026-03-12 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='additional_images',
            field=models.TextField(blank=True, default='[]', null=True),
        ),
    ]
