# Generated by Django 4.2.11 on 2026-03-12 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_product_additional_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discountPercentage',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='isDeal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.TextField(blank=True, default='{}', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='variants',
            field=models.TextField(blank=True, default='[]', null=True),
        ),
    ]
